In [1]:
import numpy as np

In [2]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
A = np.eye(4,k=2)
A

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
A = np.ndarray(9)
b = A.resize(3,3)
b

In [57]:
a = np.arange(15).reshape(3,5)
print(a)
b = np.sum(a,1)
b

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([10, 35, 60])

In [48]:
A = np.array([0,1,2,3,4])
b=np.delete(A,2,0)
b

array([0, 1, 3, 4])

In [49]:
A = np.arange(1,10,1)
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
version(pa)

NameError: name 'packagename' is not defined

In [60]:
A = np.arange(10)
A.reshape(5,2)
print(A)

[0 1 2 3 4 5 6 7 8 9]
