In [64]:
import numpy as np

In [68]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
B0 = A[1::]
B = A[-1::]
B1 = A[::-1]
B2 = A[::-2]
B3 = A[:,::-2]
B4 = A[:1,::-1]
C = A[:, ::-1]
    
print(A)
print("\n",B0)
print("\n",B)
print("\n",B1)
print("\n",B2)
print("\n",B3)
print("\n",B4)
print("\n",C)



[[1 2 3 4]
 [5 6 7 8]]

 [[5 6 7 8]]

 [[5 6 7 8]]

 [[5 6 7 8]
 [1 2 3 4]]

 [[5 6 7 8]]

 [[4 2]
 [8 6]]

 [[4 3 2 1]]

 [[4 3 2 1]
 [8 7 6 5]]
